/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinanceRouteImport } from './routes/binance'
import { Route as EscuadronRouteImport } from './routes/escuadron'
import { Route as FondosRouteImport } from './routes/fondos'
import { Route as MineriaRouteImport } from './routes/mineria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinanceRoute = BinanceRouteImport.update({
  id: '/binance',
  path: '/binance',
  getParentRoute: () => rootRouteImport,
} as any)
const EscuadronRoute = EscuadronRouteImport.update({
  id: '/escuadron',
  path: '/escuadron',
  getParentRoute: () => rootRouteImport,
} as any)
const FondosRoute = FondosRouteImport.update({
  id: '/fondos',
  path: '/fondos',
  getParentRoute: () => rootRouteImport,
} as any)
const MineriaRoute = MineriaRouteImport.update({
  id: '/mineria',
  path: '/mineria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mineria': typeof MineriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mineria': typeof MineriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mineria': typeof MineriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/binance' | '/escuadron' | '/fondos' | '/mineria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/binance' | '/escuadron' | '/fondos' | '/mineria'
  id: '__root__' | '/' | '/binance' | '/escuadron' | '/fondos' | '/mineria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinanceRoute: typeof BinanceRoute
  EscuadronRoute: typeof EscuadronRoute
  FondosRoute: typeof FondosRoute
  MineriaRoute: typeof MineriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binance': {
      id: '/binance'
      path: '/binance'
      fullPath: '/binance'
      preLoaderRoute: typeof BinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escuadron': {
      id: '/escuadron'
      path: '/escuadron'
      fullPath: '/escuadron'
      preLoaderRoute: typeof EscuadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondos': {
      id: '/fondos'
      path: '/fondos'
      fullPath: '/fondos'
      preLoaderRoute: typeof FondosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mineria': {
      id: '/mineria'
      path: '/mineria'
      fullPath: '/mineria'
      preLoaderRoute: typeof MineriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinanceRoute: BinanceRoute,
  EscuadronRoute: EscuadronRoute,
  FondosRoute: FondosRoute,
  MineriaRoute: MineriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
