/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as AutomatizacionRouteImport } from './routes/automatizacion'
import { Route as BinanceRouteImport } from './routes/binance'
import { Route as EscuadronRouteImport } from './routes/escuadron'
import { Route as FondosRouteImport } from './routes/fondos'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MineriaRouteImport } from './routes/mineria'
import { Route as ReconocimientoRouteImport } from './routes/reconocimiento'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicAutomationTickRouteImport } from './routes/api/public/automation-tick'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomatizacionRoute = AutomatizacionRouteImport.update({
  id: '/automatizacion',
  path: '/automatizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BinanceRoute = BinanceRouteImport.update({
  id: '/binance',
  path: '/binance',
  getParentRoute: () => rootRouteImport,
} as any)
const EscuadronRoute = EscuadronRouteImport.update({
  id: '/escuadron',
  path: '/escuadron',
  getParentRoute: () => rootRouteImport,
} as any)
const FondosRoute = FondosRouteImport.update({
  id: '/fondos',
  path: '/fondos',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MineriaRoute = MineriaRouteImport.update({
  id: '/mineria',
  path: '/mineria',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconocimientoRoute = ReconocimientoRouteImport.update({
  id: '/reconocimiento',
  path: '/reconocimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAutomationTickRoute = ApiPublicAutomationTickRouteImport.update({
  id: '/api/public/automation-tick',
  path: '/api/public/automation-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/automatizacion': typeof AutomatizacionRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mcp': typeof McpRoute
  '/mineria': typeof MineriaRoute
  '/reconocimiento': typeof ReconocimientoRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/automatizacion': typeof AutomatizacionRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mcp': typeof McpRoute
  '/mineria': typeof MineriaRoute
  '/reconocimiento': typeof ReconocimientoRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/automatizacion': typeof AutomatizacionRoute
  '/binance': typeof BinanceRoute
  '/escuadron': typeof EscuadronRoute
  '/fondos': typeof FondosRoute
  '/mcp': typeof McpRoute
  '/mineria': typeof MineriaRoute
  '/reconocimiento': typeof ReconocimientoRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/api/public/automation-tick': typeof ApiPublicAutomationTickRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/automatizacion'
    | '/binance'
    | '/escuadron'
    | '/fondos'
    | '/mcp'
    | '/mineria'
    | '/reconocimiento'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/automation-tick'
    | '/api/public/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/automatizacion'
    | '/binance'
    | '/escuadron'
    | '/fondos'
    | '/mcp'
    | '/mineria'
    | '/reconocimiento'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/automation-tick'
    | '/api/public/maintenance'
  id:
    | '__root__'
    | '/'
    | '/acceso'
    | '/automatizacion'
    | '/binance'
    | '/escuadron'
    | '/fondos'
    | '/mcp'
    | '/mineria'
    | '/reconocimiento'
    | '/.well-known/oauth-protected-resource'
    | '/.lovable/oauth/consent'
    | '/api/public/automation-tick'
    | '/api/public/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoRoute: typeof AccesoRoute
  AutomatizacionRoute: typeof AutomatizacionRoute
  BinanceRoute: typeof BinanceRoute
  EscuadronRoute: typeof EscuadronRoute
  FondosRoute: typeof FondosRoute
  McpRoute: typeof McpRoute
  MineriaRoute: typeof MineriaRoute
  ReconocimientoRoute: typeof ReconocimientoRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicAutomationTickRoute: typeof ApiPublicAutomationTickRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automatizacion': {
      id: '/automatizacion'
      path: '/automatizacion'
      fullPath: '/automatizacion'
      preLoaderRoute: typeof AutomatizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binance': {
      id: '/binance'
      path: '/binance'
      fullPath: '/binance'
      preLoaderRoute: typeof BinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escuadron': {
      id: '/escuadron'
      path: '/escuadron'
      fullPath: '/escuadron'
      preLoaderRoute: typeof EscuadronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fondos': {
      id: '/fondos'
      path: '/fondos'
      fullPath: '/fondos'
      preLoaderRoute: typeof FondosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mineria': {
      id: '/mineria'
      path: '/mineria'
      fullPath: '/mineria'
      preLoaderRoute: typeof MineriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconocimiento': {
      id: '/reconocimiento'
      path: '/reconocimiento'
      fullPath: '/reconocimiento'
      preLoaderRoute: typeof ReconocimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/automation-tick': {
      id: '/api/public/automation-tick'
      path: '/api/public/automation-tick'
      fullPath: '/api/public/automation-tick'
      preLoaderRoute: typeof ApiPublicAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoRoute: AccesoRoute,
  AutomatizacionRoute: AutomatizacionRoute,
  BinanceRoute: BinanceRoute,
  EscuadronRoute: EscuadronRoute,
  FondosRoute: FondosRoute,
  McpRoute: McpRoute,
  MineriaRoute: MineriaRoute,
  ReconocimientoRoute: ReconocimientoRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicAutomationTickRoute: ApiPublicAutomationTickRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
